From python:3.8.6

WORKDIR /imagesServer

ADD . /imagesServer

RUN apt-get update \
    && apt-get upgrade -y\
    && pip install --upgrade pip \
    && pip install -r requirements.txt

CMD ["uwsgi", "uwsgi.ini"]